runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css
- url: /img
  static_dir: static/img
- url: /js
  static_dir: static/js
- url: /vendor
  static_dir: static/vendor
- url: /.*
  script: main.app
